import { writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import mjml2html from 'mjml';
import {
  HERO_CARD_MJML,
  MAIN_EMAIL_MJML,
  SECTION_TITLE_MJML,
  STANDARD_CARD_MJML,
} from '../src/email/templates.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
export const OUTPUT_PATH = resolve(ROOT, 'src', 'core', 'email-layout.generated.ts');

const FRAGMENT_START = '<!--FRAGMENT_START-->';
const FRAGMENT_END = '<!--FRAGMENT_END-->';

function compileTemplate(name: string, template: string): string {
  const result = mjml2html(template, {
    beautify: false,
    minify: false,
    validationLevel: 'soft',
  });

  if (result.errors.length > 0) {
    const messages = result.errors.map(error => `${error.formattedMessage || error.message}`).join('\n');
    throw new Error(`MJML compilation failed for ${name}:\n${messages}`);
  }

  return result.html;
}

function extractFragment(name: string, html: string): string {
  const start = html.indexOf(FRAGMENT_START);
  const end = html.indexOf(FRAGMENT_END);

  if (start === -1 || end === -1 || end <= start) {
    throw new Error(`Could not extract fragment for ${name}`);
  }

  return html.slice(start + FRAGMENT_START.length, end).trim();
}

export function buildGeneratedModule() {
  let mainDocument = compileTemplate('main-document', MAIN_EMAIL_MJML);
  // WCAG 2.2: MJML defaults the HTML lang attribute to "und" (undetermined).
  // Replace with "en" so screen readers announce the correct language.
  mainDocument = mainDocument.replace(/\blang="und"/g, 'lang="en"');
  const standardCard = extractFragment('standard-card', compileTemplate('standard-card', STANDARD_CARD_MJML));
  const heroCard = extractFragment('hero-card', compileTemplate('hero-card', HERO_CARD_MJML));
  const sectionTitle = extractFragment('section-title', compileTemplate('section-title', SECTION_TITLE_MJML));

  return [
    '// This file is generated by workflow/compile-email.ts.',
    '// Do not edit it by hand.',
    '',
    `export const MAIN_EMAIL_HTML_TEMPLATE = ${JSON.stringify(mainDocument)};`,
    `export const STANDARD_CARD_HTML_TEMPLATE = ${JSON.stringify(standardCard)};`,
    `export const HERO_CARD_HTML_TEMPLATE = ${JSON.stringify(heroCard)};`,
    `export const SECTION_TITLE_HTML_TEMPLATE = ${JSON.stringify(sectionTitle)};`,
    '',
  ].join('\n');
}

export function writeCompiledTemplates(outputPath = OUTPUT_PATH) {
  writeFileSync(outputPath, buildGeneratedModule(), 'utf-8');
}

const isEntrypoint = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isEntrypoint) {
  writeCompiledTemplates();
  console.log(`Compiled email templates written to:\n  ${OUTPUT_PATH}`);
}
