import { describe, expect, it } from 'vitest';
import { bestWindows, type BestWindowsInput } from './best-windows.js';

describe('bestWindows', () => {
  it('aligns today summary metadata with the selected top window', () => {
    const input: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T18:00:00.000Z',
          t: '2026-03-14T18:00:00.000Z',
          hour: '18:00',
          score: 46,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 10,
          aod: 0,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 8,
          hum: 50,
          dew: 4,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 10,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 23,
          uv: 0,
          tags: ['landscape', 'clear light path'],
        },
        {
          ts: '2026-03-14T19:00:00.000Z',
          t: '2026-03-14T19:00:00.000Z',
          hour: '19:00',
          score: 60,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 75,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 18.3,
          aod: 0,
          tpw: 20,
          wind: 9,
          gusts: 11,
          tmp: 6,
          hum: 55,
          dew: 3,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 23,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 46,
        headlineScore: 75,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '18:00',
        bestTags: 'landscape, clear light path',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 46,
        astroScore: 75,
        astroConfidence: 'unknown',
        astroConfidenceStdDev: null,
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: 'METAR clear',
    };

    const result = bestWindows(input);

    expect(result.windows[0]?.label).toBe('Evening astro window');
    expect(result.dailySummary[0]?.bestPhotoHour).toBe('19:00');
    expect(result.dailySummary[0]?.bestTags).toBe('astrophotography');
  });

  it('distinguishes midnight astro windows from evening astro windows', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-14T01:00:00.000Z',
          t: '2026-03-14T01:00:00.000Z',
          hour: '01:00',
          score: 57,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 70,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 25.9,
          aod: 0,
          tpw: 20,
          wind: 9,
          gusts: 11,
          tmp: 4,
          hum: 55,
          dew: 3,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 22,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 42,
        headlineScore: 70,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '18:00',
        bestTags: 'landscape',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 46,
        astroScore: 70,
        astroConfidence: 'unknown',
        astroConfidenceStdDev: null,
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: 'METAR clear',
    });

    expect(result.windows[0]?.label).toBe('Midnight astro window');
  });

  it('expands a single-hour evening golden-hour window to a real time range', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-18T18:00:00.000Z',
          t: '2026-03-18T18:00:00.000Z',
          hour: '18:00',
          score: 53,
          drama: 55,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 12.6,
          aod: 0.11,
          tpw: 18,
          wind: 4,
          gusts: 6,
          tmp: 8,
          hum: 60,
          dew: 4,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 10,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 1,
          uv: 0,
          tags: ['landscape', 'golden hour'],
        },
        {
          ts: '2026-03-18T19:00:00.000Z',
          t: '2026-03-18T19:00:00.000Z',
          hour: '19:00',
          score: 40,
          drama: 40,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 11,
          aod: 0.11,
          tpw: 18,
          wind: 5,
          gusts: 7,
          tmp: 7,
          hum: 62,
          dew: 4,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 12,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 1,
          uv: 0,
          tags: ['landscape', 'golden hour'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-18',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 53,
        headlineScore: 60,
        photoEmoji: 'Marginal',
        photoRating: 'Marginal',
        bestPhotoHour: '18:00',
        bestTags: 'golden hour',
        carWash: { score: 80, rating: 'Great', label: 'Great', start: '06:00', end: '08:00', wind: 10, pp: 0, tmp: 7 },
        sunrise: '2026-03-18T06:13:00.000Z',
        sunset: '2026-03-18T18:15:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 8,
        durationBonus: 0,
        amConfidence: 'high',
        amConfidenceStdDev: 8,
        pmConfidence: 'high',
        pmConfidenceStdDev: 8,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 50,
        pmScore: 57,
        astroScore: 68,
        bestAstroHour: '03:00',
        darkSkyStartsAt: '00:00',
        bestAmHour: '06:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
        astroConfidence: 'high',
        astroConfidenceStdDev: 7,
      }],
      metarNote: '',
    });

    expect(result.windows[0]?.label).toBe('Evening golden hour');
    expect(result.windows[0]?.start).toBe('18:00');
    expect(result.windows[0]?.end).toBe('19:00');
    expect(result.windows[0]?.hours).toHaveLength(2);
  });

  it('labels a pre-dawn astro window (04:00) correctly', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-14T04:00:00.000Z',
          t: '2026-03-14T04:00:00.000Z',
          hour: '04:00',
          score: 57,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 70,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 25.9,
          aod: 0,
          tpw: 20,
          wind: 9,
          gusts: 11,
          tmp: 4,
          hum: 55,
          dew: 3,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 22,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 42,
        headlineScore: 70,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '18:00',
        bestTags: 'landscape',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 46,
        astroScore: 70,
        astroConfidence: 'unknown',
        astroConfidenceStdDev: null,
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: 'METAR clear',
    });

    expect(result.windows[0]?.label).toBe('Pre-dawn astro window');
  });

  it('marks a moonset that falls inside a window and computes the dark-phase score separately', () => {
    const input: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T22:00:00.000Z',
          t: '2026-03-14T22:00:00.000Z',
          hour: '22:00',
          score: 58,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 58,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 20,
          aod: 0.05,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 5,
          hum: 60,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
        {
          ts: '2026-03-14T23:00:00.000Z',
          t: '2026-03-14T23:00:00.000Z',
          hour: '23:00',
          score: 76,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 76,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 22,
          aod: 0.05,
          tpw: 20,
          wind: 7,
          gusts: 9,
          tmp: 4,
          hum: 58,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
        {
          ts: '2026-03-15T00:00:00.000Z',
          t: '2026-03-15T00:00:00.000Z',
          hour: '00:00',
          score: 84,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 84,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 24,
          aod: 0.05,
          tpw: 20,
          wind: 6,
          gusts: 8,
          tmp: 4,
          hum: 55,
          dew: 1,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 40,
        headlineScore: 84,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '22:00',
        bestTags: 'astrophotography',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 0,
        pmScore: 0,
        astroScore: 84,
        bestAstroHour: '00:00',
        darkSkyStartsAt: '23:00',
        bestAmHour: '—',
        bestPmHour: '—',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
        astroConfidence: 'unknown', astroConfidenceStdDev: null,
      }],
      metarNote: '',
    };

    const result = bestWindows(input);

    expect(result.windows[0]?.darkPhaseStart).toBe('23:00');
    expect(result.windows[0]?.postMoonsetScore).toBe(84);
  });

  it('leaves windows unchanged when moonset is before or after the window', () => {
    const baseInput: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T19:00:00.000Z',
          t: '2026-03-14T19:00:00.000Z',
          hour: '19:00',
          score: 58,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 70,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 20,
          aod: 0,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 5,
          hum: 60,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 20,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 40,
        headlineScore: 70,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '19:00',
        bestTags: 'astrophotography',
        carWash: { score: 60, rating: 'OK', label: 'Usable', start: '15:00', end: '17:00', wind: 14, pp: 24, tmp: 9 },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 0,
        pmScore: 0,
        astroScore: 70,
        bestAstroHour: '19:00',
        darkSkyStartsAt: '01:00',
        bestAmHour: '—',
        bestPmHour: '—',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
        astroConfidence: 'unknown', astroConfidenceStdDev: null,
      }],
      metarNote: '',
    };

    const afterWindow = bestWindows(baseInput);
    const beforeWindow = bestWindows({
      ...baseInput,
      dailySummary: [{ ...baseInput.dailySummary[0], darkSkyStartsAt: '18:00' }],
    });

    expect(afterWindow.windows[0]?.darkPhaseStart).toBeUndefined();
    expect(afterWindow.windows[0]?.postMoonsetScore).toBeUndefined();
    expect(beforeWindow.windows[0]?.darkPhaseStart).toBeUndefined();
    expect(beforeWindow.windows[0]?.postMoonsetScore).toBeUndefined();
  });

  it('forces a no-window day into dontBother even if the incoming headline is overstated', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-16T04:00:00.000Z',
          t: '2026-03-16T04:00:00.000Z',
          hour: '04:00',
          score: 42,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 52,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 3,
          ct: 3,
          visK: 20.5,
          aod: 0.09,
          tpw: 10,
          wind: 6,
          gusts: 8,
          tmp: 4,
          hum: 60,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 8,
          uv: 0,
          tags: ['astrophotography'],
        },
        {
          ts: '2026-03-16T07:00:00.000Z',
          t: '2026-03-16T07:00:00.000Z',
          hour: '07:00',
          score: 32,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 20,
          ct: 20,
          visK: 15,
          aod: 0.1,
          tpw: 12,
          wind: 10,
          gusts: 12,
          tmp: 5,
          hum: 70,
          dew: 3,
          pp: 10,
          pr: 0,
          vpd: 0,
          azimuthRisk: 10,
          isGolden: true,
          isGoldAm: true,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 8,
          uv: 0,
          tags: ['landscape', 'clear light path'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-16',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 32,
        headlineScore: 52,
        photoEmoji: 'Marginal',
        photoRating: 'Marginal',
        bestPhotoHour: '07:00',
        bestTags: 'landscape, clear light path',
        carWash: { score: 60, rating: 'OK', label: 'Usable', start: '06:00', end: '08:00', wind: 12, pp: 22, tmp: 5 },
        sunrise: '2026-03-16T06:18:00.000Z',
        sunset: '2026-03-16T18:11:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 5,
        durationBonus: 0,
        amConfidence: 'high',
        amConfidenceStdDev: 5,
        pmConfidence: 'high',
        pmConfidenceStdDev: 5,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 15,
        astroScore: 52,
        bestAstroHour: '04:00',
        darkSkyStartsAt: '00:00',
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: 10,
        sunsetOcclusionRisk: null,
        astroConfidence: 'high',
        astroConfidenceStdDev: 11,
      }],
      metarNote: '',
    });

    expect(result.windows).toEqual([]);
    expect(result.dontBother).toBe(true);
    expect(result.todayBestScore).toBe(47);
  });

  it('prefers a strong specialist session fallback when it materially beats the generic fallback', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-30T03:00:00.000Z',
          t: '2026-03-30T03:00:00.000Z',
          hour: '03:00',
          score: 2,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 98,
          ct: 98,
          visK: 11,
          aod: 0.09,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 6,
          hum: 90,
          dew: 5,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 87,
          uv: 0,
          tags: ['urban'],
        },
        {
          ts: '2026-03-30T20:00:00.000Z',
          t: '2026-03-30T20:00:00.000Z',
          hour: '20:00',
          score: 34,
          drama: 54,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 20,
          ct: 30,
          visK: 44,
          aod: 0.07,
          tpw: 20,
          wind: 11,
          gusts: 14,
          tmp: 11,
          hum: 70,
          dew: 7,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 20,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 87,
          uv: 0,
          tags: ['landscape'],
        },
        {
          ts: '2026-03-30T21:00:00.000Z',
          t: '2026-03-30T21:00:00.000Z',
          hour: '21:00',
          score: 40,
          drama: 21,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 41,
          aod: 0.06,
          tpw: 20,
          wind: 9,
          gusts: 12,
          tmp: 10,
          hum: 68,
          dew: 6,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 18,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: true,
          isBlueAm: false,
          isBluePm: true,
          isNight: false,
          moon: 87,
          uv: 0,
          tags: ['landscape'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-30',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 47,
        headlineScore: 47,
        photoEmoji: 'Marginal',
        photoRating: 'Marginal',
        bestPhotoHour: '21:00',
        bestTags: 'landscape',
        carWash: { score: 95, rating: 'Great', label: 'Great', start: '08:00', end: '10:00', wind: 16, pp: 0, tmp: 8 },
        sunrise: '2026-03-30T07:43:00.000Z',
        sunset: '2026-03-30T20:37:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'medium',
        confidenceStdDev: 20,
        durationBonus: 0,
        amConfidence: 'low',
        amConfidenceStdDev: 20,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 18,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 26,
        pmScore: 44,
        astroScore: 41,
        astroConfidence: 'medium',
        astroConfidenceStdDev: 24,
        bestAmHour: '07:00',
        bestPmHour: '21:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: '',
      sessionRecommendation: {
        primary: {
          session: 'urban',
          hourLabel: '03:00',
          score: 67,
          hardPass: true,
          confidence: 'low',
          volatility: 22,
          reasons: ['Wet streets and city light should hold up best before dawn.'],
          warnings: [],
          requiredCapabilities: [],
        },
        runnerUps: [],
        bySession: [],
        hoursAnalyzed: 24,
        planB: null,
        alerts: [],
      },
    });

    expect(result.windows[0]?.label).toBe('Best urban session');
    expect(result.windows[0]?.start).toBe('03:00');
    expect(result.windows[0]?.peak).toBe(67);
    expect(result.dontBother).toBe(false);
    expect(result.todayBestScore).toBe(47);
    expect(result.dailySummary[0]?.bestPhotoHour).toBe('03:00');
    expect(result.dailySummary[0]?.bestTags).toBe('urban');
    expect(result.debugContext.windows[0]?.selectionReason).toContain('strongest session recommendation');
  });

  it('caps todayBestScore at the best window peak even when headlineScore is higher', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-14T18:00:00.000Z',
          t: '2026-03-14T18:00:00.000Z',
          hour: '18:00',
          score: 55,
          drama: 50,
          clarity: 40,
          mist: 30,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 20,
          cm: 15,
          ch: 10,
          ct: 30,
          visK: 18,
          aod: 0.08,
          tpw: 16,
          wind: 8,
          gusts: 10,
          tmp: 10,
          hum: 55,
          dew: 4,
          pp: 5,
          pr: 0,
          vpd: 0,
          azimuthRisk: 10,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 12,
          uv: 0,
          tags: ['golden hour'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 62,
        headlineScore: 62,
        photoEmoji: 'Good',
        photoRating: 'Good',
        bestPhotoHour: '18:00',
        bestTags: 'golden hour',
        carWash: { score: 70, rating: 'OK', label: 'Usable', start: '10:00', end: '12:00', wind: 8, pp: 5, tmp: 10 },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 8,
        durationBonus: 7,
        amConfidence: 'high',
        amConfidenceStdDev: 8,
        pmConfidence: 'high',
        pmConfidenceStdDev: 8,
        goldAmMins: 45,
        goldPmMins: 55,
        amScore: 0,
        pmScore: 55,
        astroScore: 0,
        bestAmHour: '—',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: 10,
        astroConfidence: 'unknown',
        astroConfidenceStdDev: null,
      }],
      metarNote: '',
    });

    // The day score must not exceed the best window peak
    expect(result.todayBestScore).toBeLessThanOrEqual(result.windows[0]?.peak ?? 0);
    expect(result.todayBestScore).toBe(55);
  });
});
