import { describe, expect, it } from 'vitest';
import { bestWindows, type BestWindowsInput } from './best-windows.js';

describe('bestWindows', () => {
  it('aligns today summary metadata with the selected top window', () => {
    const input: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T18:00:00.000Z',
          t: '2026-03-14T18:00:00.000Z',
          hour: '18:00',
          score: 46,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 0,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 10,
          aod: 0,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 8,
          hum: 50,
          dew: 4,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: 10,
          isGolden: true,
          isGoldAm: false,
          isGoldPm: true,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: false,
          moon: 23,
          uv: 0,
          tags: ['landscape', 'clear light path'],
        },
        {
          ts: '2026-03-14T19:00:00.000Z',
          t: '2026-03-14T19:00:00.000Z',
          hour: '19:00',
          score: 60,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 75,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 18.3,
          aod: 0,
          tpw: 20,
          wind: 9,
          gusts: 11,
          tmp: 6,
          hum: 55,
          dew: 3,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 23,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 46,
        headlineScore: 75,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '18:00',
        bestTags: 'landscape, clear light path',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 46,
        astroScore: 75,
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: 'METAR clear',
    };

    const result = bestWindows(input);

    expect(result.windows[0]?.label).toBe('Evening astro window');
    expect(result.dailySummary[0]?.bestPhotoHour).toBe('19:00');
    expect(result.dailySummary[0]?.bestTags).toBe('astrophotography');
  });

  it('distinguishes overnight astro windows from evening astro windows', () => {
    const result = bestWindows({
      todayHours: [
        {
          ts: '2026-03-14T01:00:00.000Z',
          t: '2026-03-14T01:00:00.000Z',
          hour: '01:00',
          score: 57,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 70,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 25.9,
          aod: 0,
          tpw: 20,
          wind: 9,
          gusts: 11,
          tmp: 4,
          hum: 55,
          dew: 3,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 22,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 42,
        headlineScore: 70,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '18:00',
        bestTags: 'landscape',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 32,
        pmScore: 46,
        astroScore: 70,
        bestAmHour: '07:00',
        bestPmHour: '18:00',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: 'METAR clear',
    });

    expect(result.windows[0]?.label).toBe('Overnight astro window');
  });

  it('marks a moonset that falls inside a window and computes the dark-phase score separately', () => {
    const input: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T22:00:00.000Z',
          t: '2026-03-14T22:00:00.000Z',
          hour: '22:00',
          score: 58,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 58,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 20,
          aod: 0.05,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 5,
          hum: 60,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
        {
          ts: '2026-03-14T23:00:00.000Z',
          t: '2026-03-14T23:00:00.000Z',
          hour: '23:00',
          score: 76,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 76,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 22,
          aod: 0.05,
          tpw: 20,
          wind: 7,
          gusts: 9,
          tmp: 4,
          hum: 58,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
        {
          ts: '2026-03-15T00:00:00.000Z',
          t: '2026-03-15T00:00:00.000Z',
          hour: '00:00',
          score: 84,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 84,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 24,
          aod: 0.05,
          tpw: 20,
          wind: 6,
          gusts: 8,
          tmp: 4,
          hum: 55,
          dew: 1,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 60,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 40,
        headlineScore: 84,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '22:00',
        bestTags: 'astrophotography',
        carWash: {
          score: 60,
          rating: 'OK',
          label: 'Usable',
          start: '15:00',
          end: '17:00',
          wind: 14,
          pp: 24,
          tmp: 9,
        },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 0,
        pmScore: 0,
        astroScore: 84,
        bestAstroHour: '00:00',
        darkSkyStartsAt: '23:00',
        bestAmHour: '—',
        bestPmHour: '—',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: '',
    };

    const result = bestWindows(input);

    expect(result.windows[0]?.darkPhaseStart).toBe('23:00');
    expect(result.windows[0]?.postMoonsetScore).toBe(84);
  });

  it('leaves windows unchanged when moonset is before or after the window', () => {
    const baseInput: BestWindowsInput = {
      todayHours: [
        {
          ts: '2026-03-14T19:00:00.000Z',
          t: '2026-03-14T19:00:00.000Z',
          hour: '19:00',
          score: 58,
          drama: 0,
          clarity: 0,
          mist: 0,
          astro: 70,
          crepuscular: 0,
          shQ: null,
          cl: 0,
          cm: 0,
          ch: 0,
          ct: 0,
          visK: 20,
          aod: 0,
          tpw: 20,
          wind: 8,
          gusts: 10,
          tmp: 5,
          hum: 60,
          dew: 2,
          pp: 0,
          pr: 0,
          vpd: 0,
          azimuthRisk: null,
          isGolden: false,
          isGoldAm: false,
          isGoldPm: false,
          isBlue: false,
          isBlueAm: false,
          isBluePm: false,
          isNight: true,
          moon: 20,
          uv: 0,
          tags: ['astrophotography'],
        },
      ],
      dailySummary: [{
        dateKey: '2026-03-14',
        dayLabel: 'Today',
        dayIdx: 0,
        hours: [],
        photoScore: 40,
        headlineScore: 70,
        photoEmoji: 'Excellent',
        photoRating: 'Excellent',
        bestPhotoHour: '19:00',
        bestTags: 'astrophotography',
        carWash: { score: 60, rating: 'OK', label: 'Usable', start: '15:00', end: '17:00', wind: 14, pp: 24, tmp: 9 },
        sunrise: '2026-03-14T06:23:00.000Z',
        sunset: '2026-03-14T18:07:00.000Z',
        shSunsetQuality: null,
        shSunriseQuality: null,
        shSunsetText: null,
        sunDirection: null,
        crepRayPeak: 0,
        confidence: 'high',
        confidenceStdDev: 10,
        durationBonus: 0,
        amConfidence: 'medium',
        amConfidenceStdDev: 10,
        pmConfidence: 'medium',
        pmConfidenceStdDev: 10,
        goldAmMins: 0,
        goldPmMins: 0,
        amScore: 0,
        pmScore: 0,
        astroScore: 70,
        bestAstroHour: '19:00',
        darkSkyStartsAt: '01:00',
        bestAmHour: '—',
        bestPmHour: '—',
        sunriseOcclusionRisk: null,
        sunsetOcclusionRisk: null,
      }],
      metarNote: '',
    };

    const afterWindow = bestWindows(baseInput);
    const beforeWindow = bestWindows({
      ...baseInput,
      dailySummary: [{ ...baseInput.dailySummary[0], darkSkyStartsAt: '18:00' }],
    });

    expect(afterWindow.windows[0]?.darkPhaseStart).toBeUndefined();
    expect(afterWindow.windows[0]?.postMoonsetScore).toBeUndefined();
    expect(beforeWindow.windows[0]?.darkPhaseStart).toBeUndefined();
    expect(beforeWindow.windows[0]?.postMoonsetScore).toBeUndefined();
  });
});
